version: '3.3'

services:
  frontend:
    container_name: drink-lovers-frontend
    image: node:latest
    restart: always
    working_dir: "/home/node/app"
    ports: 
        - 8081:8080
    volumes: 
        - ./:/home/node/app
    command: "npm install yarn"
    command: "yarn global add @vue/cli"
    command: "yarn install"
    command: "yarn serve"
    # command: "ping 192.168.73.3"